apiVersion: v1
kind: Service
metadata:
  namespace: dsmhack-2025-cultivate
  name: shopeatlocal-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dsmhack-2025-cultivate
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - image: mysql:9
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: shopeatlocal
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mysql-secrets
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root-password
                  name: mysql-secrets
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: 1024Mi
              cpu: 1000m
            requests:
              memory: 512Mi
              cpu: 200m
          readinessProbe:
            tcpSocket:
              port: 3306
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: dump
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: dsmhack-2025-cultivate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
