CREATE TABLE MemberTags (
    IDMemberTag INT AUTO_INCREMENT PRIMARY KEY,
    Tag VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE MemberTagAssignments (
    IDMemberTagAssignment INT AUTO_INCREMENT PRIMARY KEY,
    IDMemberTag INT NOT NULL,
    IDMemb INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (IDMemberTag) REFERENCES MemberTags (IDMemberTag) ON DELETE CASCADE,
    FOREIGN KEY (IDMemb) REFERENCES Memb (IDMemb) ON DELETE CASCADE
);

INSERT INTO MemberTags (Tag) VALUES ('farmers friend');

INSERT INTO MemberTags (Tag) VALUES ('sustaining steward');

INSERT INTO MemberTags (Tag) VALUES ('community cultivator');

INSERT INTO MemberTags (Tag) VALUES ('keep anonymous');