ALTER TABLE `Transact`
MODIFY COLUMN `CdMethPay` enum('Cash','Check','Credit','Debit','PayPal','Square','GiftCert','Coupon','EBTElec','EBTVouch') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL;

CREATE TABLE IF NOT EXISTS `SquareTerminal` (
  `IDSquareTerminal` int NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SquareLocationID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SquareDeviceCodeID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SquareDeviceCode` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SquareDeviceID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CdStatusSquareTerminal` enum('Pending','Paired','Expired','Disabled') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Pending',
  `CkActive` tinyint NOT NULL DEFAULT '1',
  `IDMembStaffCreate` int DEFAULT NULL,
  `IDMembStaffUpdate` int DEFAULT NULL,
  `WhenCreate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `WhenUpdate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`IDSquareTerminal`),
  UNIQUE KEY `uqSquareTerminal-SquareDeviceCodeID` (`SquareDeviceCodeID`),
  UNIQUE KEY `uqSquareTerminal-SquareDeviceID` (`SquareDeviceID`),
  KEY `kSquareTerminal-IDMembStaffCreate` (`IDMembStaffCreate`),
  KEY `kSquareTerminal-IDMembStaffUpdate` (`IDMembStaffUpdate`),
  CONSTRAINT `kSquareTerminal-IDMembStaffCreate` FOREIGN KEY (`IDMembStaffCreate`) REFERENCES `Memb` (`IDMemb`),
  CONSTRAINT `kSquareTerminal-IDMembStaffUpdate` FOREIGN KEY (`IDMembStaffUpdate`) REFERENCES `Memb` (`IDMemb`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `SquareMemberPaymentProfile` (
  `IDSquareMemberPaymentProfile` int NOT NULL AUTO_INCREMENT,
  `IDMemb` int NOT NULL,
  `SquareCustomerID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SquareCardID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CardBrand` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CardLast4` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CardExpMonth` tinyint unsigned DEFAULT NULL,
  `CardExpYear` smallint unsigned DEFAULT NULL,
  `CkAutoCharge` tinyint NOT NULL DEFAULT '0',
  `WhenAutoChargeConsent` datetime DEFAULT NULL,
  `WhenAutoChargeDisable` datetime DEFAULT NULL,
  `WhenCardCreate` datetime DEFAULT NULL,
  `WhenCardDisable` datetime DEFAULT NULL,
  `WhenCreate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `WhenUpdate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`IDSquareMemberPaymentProfile`),
  UNIQUE KEY `uqSquareMemberPaymentProfile-IDMemb` (`IDMemb`),
  UNIQUE KEY `uqSquareMemberPaymentProfile-SquareCustomerID` (`SquareCustomerID`),
  UNIQUE KEY `uqSquareMemberPaymentProfile-SquareCardID` (`SquareCardID`),
  CONSTRAINT `kSquareMemberPaymentProfile-IDMemb` FOREIGN KEY (`IDMemb`) REFERENCES `Memb` (`IDMemb`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `SquareMemberPaymentProfileEvent` (
  `IDSquareMemberPaymentProfileEvent` int NOT NULL AUTO_INCREMENT,
  `IDSquareMemberPaymentProfile` int NOT NULL,
  `IDMemb` int NOT NULL,
  `CdEventSquareMemberPaymentProfile` enum('CustomerCreate','CardSave','CardReplace','CardDisable','AutoChargeOptIn','AutoChargeOptOut') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SquareCustomerID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SquareCardID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `IDMembStaffCreate` int DEFAULT NULL,
  `Note` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `WhenCreate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IDSquareMemberPaymentProfileEvent`),
  KEY `kSquareMemberPaymentProfileEvent-IDSquareMemberPaymentProfile` (`IDSquareMemberPaymentProfile`),
  KEY `kSquareMemberPaymentProfileEvent-IDMemb` (`IDMemb`),
  KEY `kSquareMemberPaymentProfileEvent-IDMembStaffCreate` (`IDMembStaffCreate`),
  CONSTRAINT `kSquareMemberPaymentProfileEvent-IDSquareMemberPaymentProfile` FOREIGN KEY (`IDSquareMemberPaymentProfile`) REFERENCES `SquareMemberPaymentProfile` (`IDSquareMemberPaymentProfile`),
  CONSTRAINT `kSquareMemberPaymentProfileEvent-IDMemb` FOREIGN KEY (`IDMemb`) REFERENCES `Memb` (`IDMemb`),
  CONSTRAINT `kSquareMemberPaymentProfileEvent-IDMembStaffCreate` FOREIGN KEY (`IDMembStaffCreate`) REFERENCES `Memb` (`IDMemb`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `SquareCheckout` (
  `IDSquareCheckout` int NOT NULL AUTO_INCREMENT,
  `IDMemb` int NOT NULL,
  `IDMembStaffCreate` int NOT NULL,
  `IDSquareTerminal` int DEFAULT NULL,
  `IDSquareMemberPaymentProfile` int DEFAULT NULL,
  `IDTransact` int DEFAULT NULL,
  `CdTypeSquareCheckout` enum('Terminal','Cash','AutoCharge','WebCard') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CdStatusSquareCheckout` enum('Pending','InProgress','Completed','Canceled','Failed') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Pending',
  `AmtMoney` decimal(9,2) NOT NULL,
  `AmtCashTendered` decimal(9,2) DEFAULT NULL,
  `SquareLocationID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SquareIdempotencyKey` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SquareTerminalCheckoutID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SquarePaymentID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SquareOrderID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SquareReceiptURL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SquareStatus` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SquareResponseJSON` json DEFAULT NULL,
  `SquareErrorJSON` json DEFAULT NULL,
  `LastSquareWebhookEventID` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `WhenCreate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `WhenUpdate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `WhenComplete` datetime DEFAULT NULL,
  PRIMARY KEY (`IDSquareCheckout`),
  UNIQUE KEY `uqSquareCheckout-SquareIdempotencyKey` (`SquareIdempotencyKey`),
  UNIQUE KEY `uqSquareCheckout-SquareTerminalCheckoutID` (`SquareTerminalCheckoutID`),
  UNIQUE KEY `uqSquareCheckout-SquarePaymentID` (`SquarePaymentID`),
  UNIQUE KEY `uqSquareCheckout-IDTransact` (`IDTransact`),
  KEY `kSquareCheckout-IDMemb` (`IDMemb`),
  KEY `kSquareCheckout-IDMembStaffCreate` (`IDMembStaffCreate`),
  KEY `kSquareCheckout-IDSquareTerminal` (`IDSquareTerminal`),
  KEY `kSquareCheckout-IDSquareMemberPaymentProfile` (`IDSquareMemberPaymentProfile`),
  KEY `kSquareCheckout-LastSquareWebhookEventID` (`LastSquareWebhookEventID`),
  CONSTRAINT `kSquareCheckout-IDMemb` FOREIGN KEY (`IDMemb`) REFERENCES `Memb` (`IDMemb`),
  CONSTRAINT `kSquareCheckout-IDMembStaffCreate` FOREIGN KEY (`IDMembStaffCreate`) REFERENCES `Memb` (`IDMemb`),
  CONSTRAINT `kSquareCheckout-IDSquareTerminal` FOREIGN KEY (`IDSquareTerminal`) REFERENCES `SquareTerminal` (`IDSquareTerminal`),
  CONSTRAINT `kSquareCheckout-IDSquareMemberPaymentProfile` FOREIGN KEY (`IDSquareMemberPaymentProfile`) REFERENCES `SquareMemberPaymentProfile` (`IDSquareMemberPaymentProfile`),
  CONSTRAINT `kSquareCheckout-IDTransact` FOREIGN KEY (`IDTransact`) REFERENCES `Transact` (`IDTransact`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `SquareWebhookEvent` (
  `IDSquareWebhookEvent` int NOT NULL AUTO_INCREMENT,
  `SquareEventID` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CdTypeSquareWebhookEvent` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SquareMerchantID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SquareEnvironment` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SquareObjectID` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PayloadJSON` json NOT NULL,
  `CkProcessed` tinyint NOT NULL DEFAULT '0',
  `WhenEvent` datetime DEFAULT NULL,
  `WhenReceived` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `WhenProcessed` datetime DEFAULT NULL,
  `Error` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  PRIMARY KEY (`IDSquareWebhookEvent`),
  UNIQUE KEY `uqSquareWebhookEvent-SquareEventID` (`SquareEventID`),
  KEY `kSquareWebhookEvent-SquareObjectID` (`SquareObjectID`),
  KEY `kSquareWebhookEvent-CkProcessed` (`CkProcessed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
